<a href="https://colab.research.google.com/github/Nurulhasanah2/Analisis-Sentimen-Bibit-Dengan-Metode-SVM-dan-Logistic-Regression-Berdasarkan-Ulasan-PlayStore/blob/main/Analisis_Sentimen_Bibit_dengan_metode_Support_Vector_Machine_dan_Logistic_Regression_Berdasarkan_Ulasan_di_Google_Play_Store.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google-play-scraper-1.0.3.tar.gz (52 kB)
     |‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 52 kB 1.2 MB/s
Building wheels for collected packages: google-play-scraper
  Building wheel for google-play-scraper (setup.py) ... done
  Created wheel for google-play-scraper: filename=google_play_scraper-1.0.3-py3-none-any.whl size=24394 sha256=77ae90a4c961ddc827d260599c1d82f7b5488a09b93290335ef8e51ae02c3bf9
  Stored in directory: /root/.cache/pip/wheels/81/37/0b/4a14be55b449a048cd93d79930b1a980dee7896480defa1923
Successfully built google-play-scraper
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.0.3

In [2]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [3]:
from google_play_scraper import Sort, reviews_all
us_reviews = reviews_all(
    'com.bibit.bibitid',
    sleep_milliseconds=0, # defaults to 0
    lang='id', # defaults to 'en'
    country='id', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT
    count=3000,
)

In [4]:
df_data = pd.DataFrame(np.array(us_reviews),columns=['review'])
df_data = df_data.join(pd.DataFrame(df_data.pop('review').tolist()))
df_data.head()

                                            reviewId  ... repliedAt
0  gp:AOqpTOEzje9e5_3mVKYwz_FspimHME0DYfL922e_fDd...  ...       NaT
1  gp:AOqpTOGDS08kY3ImttJpOu83M23ZMBaoywfCgrhLrtR...  ...       NaT
2  gp:AOqpTOG4fvFiEpsYXCxQAnBX1A-l81T3WC7U8CbmYZD...  ...       NaT
3  gp:AOqpTOHdv2uxYtmwBD-dMGAR4PWDK8STyQ4icTmjrRp...  ...       NaT
4  gp:AOqpTOFgr0lbCnYAUzvG7xsdCYAkv1iIx988vV3eycW...  ...       NaT

[5 rows x 10 columns]

In [5]:
len(df_data)

36064

In [6]:
df_data[['userName', 'score','at', 'content']].head()

       userName  ...                                            content
0  Mamin Mizura  ...  Mudah2an bibit bisa tumbuh memberikan keuntung...
1   budie tarie  ...  insyah allah sangat membantu masyarakat aplika...
2    LOE HEROES  ...                                       Apknya bagus
3    TRI ADMOJO  ...  Agar mendapatkan keuntungan dari daftar sebesa...
4     Bawik Edi  ...                                               üëçüëçüëçüëç

[5 rows x 4 columns]

In [7]:
review = df_data[['userName', 'score','at', 'content']]
sorted_df = review.sort_values(by='at', ascending=False) 
sorted_df.head()

       userName  ...                                            content
0  Mamin Mizura  ...  Mudah2an bibit bisa tumbuh memberikan keuntung...
1   budie tarie  ...  insyah allah sangat membantu masyarakat aplika...
2    LOE HEROES  ...                                       Apknya bagus
3    TRI ADMOJO  ...  Agar mendapatkan keuntungan dari daftar sebesa...
4     Bawik Edi  ...                                               üëçüëçüëçüëç

[5 rows x 4 columns]

In [8]:
ss = sorted_df[['userName', 'score','at', 'content']]

In [9]:
ss.head()

       userName  ...                                            content
0  Mamin Mizura  ...  Mudah2an bibit bisa tumbuh memberikan keuntung...
1   budie tarie  ...  insyah allah sangat membantu masyarakat aplika...
2    LOE HEROES  ...                                       Apknya bagus
3    TRI ADMOJO  ...  Agar mendapatkan keuntungan dari daftar sebesa...
4     Bawik Edi  ...                                               üëçüëçüëçüëç

[5 rows x 4 columns]

In [10]:
ss.to_csv("ReviewBibit.csv", index = False)

In [11]:
pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (3.2.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from nltk) (1.15.0)

In [12]:
import pandas as pd 
import re 
import string 
import nltk 
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [13]:
review = pd.read_csv("ReviewBibit.csv")
review.head()

       userName  ...                                            content
0  Mamin Mizura  ...  Mudah2an bibit bisa tumbuh memberikan keuntung...
1   budie tarie  ...  insyah allah sangat membantu masyarakat aplika...
2    LOE HEROES  ...                                       Apknya bagus
3    TRI ADMOJO  ...  Agar mendapatkan keuntungan dari daftar sebesa...
4     Bawik Edi  ...                                               üëçüëçüëçüëç

[5 rows x 4 columns]

In [14]:
review = review[['content', 'score']]
review.head()

                                             content  score
0  Mudah2an bibit bisa tumbuh memberikan keuntung...      5
1  insyah allah sangat membantu masyarakat aplika...      5
2                                       Apknya bagus      5
3  Agar mendapatkan keuntungan dari daftar sebesa...      5
4                                               üëçüëçüëçüëç      5

In [15]:
review = review[review.score != 3]

pd.set_option('mode.chained_assignment', None)
review["labels"] = review["score"].apply(lambda x: 1 if x < 3  else 0) 
df = review.drop("score",axis=1)

df.head()

                                             content  labels
0  Mudah2an bibit bisa tumbuh memberikan keuntung...       0
1  insyah allah sangat membantu masyarakat aplika...       0
2                                       Apknya bagus       0
3  Agar mendapatkan keuntungan dari daftar sebesa...       0
4                                               üëçüëçüëçüëç       0

In [16]:
from nltk.corpus import stopwords 
from nltk.tokenize import sent_tokenize, word_tokenize

In [17]:
def pre_process(Review_Text):

    Review_Text = str(Review_Text).lower()
    Review_Text = re.sub(r"\d+", "", Review_Text)
    Review_Text = Review_Text.translate(str.maketrans("","",string.punctuation))
    Review_Text = Review_Text.strip()
    pisah = Review_Text.split()
    tokens = nltk.tokenize.word_tokenize(Review_Text)
    listStopword =  set(stopwords.words('indonesian'))
 
    removed = []
    for t in tokens:
      if t not in listStopword:
        removed.append(t)

    return Review_Text

df['content'] = df['content'].apply(lambda x:pre_process(x))
df.head()

                                             content  labels
0  mudahan bibit bisa tumbuh memberikan keuntunga...       0
1  insyah allah sangat membantu masyarakat aplika...       0
2                                       apknya bagus       0
3  agar mendapatkan keuntungan dari daftar sebesa...       0
4                                               üëçüëçüëçüëç       0

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv.fit(df['content'])
X = cv.transform(df['content'])

y = df['labels']

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.80)

In [20]:
for c in [0.01, 0.05, 0.25, 0.5, 1]:
    
    lr = LogisticRegression(C=c)
    lr.fit(X_train, y_train)
    print('Accuracy for C=%s: %s'
         % (c, accuracy_score(y_test, lr.predict(X_test))))

Accuracy for C=0.01: 0.9185336048879837
Accuracy for C=0.05: 0.9354087867326156
Accuracy for C=0.25: 0.9429735234215886
Accuracy for C=0.5: 0.9445737561827174
Accuracy for C=1: 0.9448647075938318

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [21]:
for c in [0.01, 0.05, 0.25, 0.5, 1]:
    
    sv = SVC(C=c)
    sv.fit(X_train, y_train)
    print('Accuracy for C=%s: %s'
         % (c, accuracy_score(y_test, sv.predict(X_test))))

Accuracy for C=0.01: 0.884055862670934
Accuracy for C=0.05: 0.8876927553098632
Accuracy for C=0.25: 0.9116962467267966
Accuracy for C=0.5: 0.924643584521385
Accuracy for C=1: 0.9352633110270585

In [22]:
final_model_lr = LogisticRegression(C=1)
final_model_lr.fit(X, y)
print('Final Model Accuracy: %s' %accuracy_score(y_test, final_model_lr.predict(X_test)))

Final Model Accuracy: 0.9711958102996799

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [23]:
final_model_sv = SVC(C=1)
final_model_sv.fit(X, y)
print('Final Model Accuracy: %s' %accuracy_score(y_test, final_model_sv.predict(X_test)))

Final Model Accuracy: 0.9810881582775677